// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATableSummary: typeof import('ant-design-vue/es')['TableSummary']
    ATableSummaryCell: typeof import('ant-design-vue/es')['TableSummaryCell']
    ATableSummaryRow: typeof import('ant-design-vue/es')['TableSummaryRow']
    PageA: typeof import('./src/components/PageA.vue')['default']
    PageB: typeof import('./src/components/PageB.vue')['default']
    PageC: typeof import('./src/components/PageC.vue')['default']
    PageD: typeof import('./src/components/PageD.vue')['default']
    PageE: typeof import('./src/components/PageE.vue')['default']
  }
}

export {}
